### ISSUE TITLE
Add support for custom products

### ISSUE THREAD

**Issue by Skydiver777** [FriendsOfShopware/FroshVariantSwitch#2]
# Prerequisites

## Actual behaviour
Switching a variation in basket opens the variation in basket. However it does not include settings the user had made using custom product options. 

## Expected behaviour
The switch variation button opens the temporary created custom product, this link is already available in the cart by default.

## Environment

    Please provide information about the environment in which the issue occurs (e.g. PHP version, webserver, Shopware version, debugging information if you can provide).

## Steps to reproduce
Create custom product in backend
add custom product to cart
edit this product

## Checklist

- [x ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshVariantSwitch/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ x] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by dneustadt** [comment]
Hi @Skydiver777 
even though we would love to find a solution for this issue, we simply can't guarantee for it to behave as you are expecting in the foreseeable future. While many of us work at service providers and have had at least some experience with Shopware's commercial products, this project is still a non-profit endeavor. This is why the support of the open-source Community Edition is our main focus. Custom Products is a very complex extension and it would take a lot of reverse engineering to make all of its features available in the context of the Variant Switch modal. If the current behaviour is likely to confuse customers it might be the best option to simply not offer a variant switch link for custom products. That might be something that could be implemented in a reasonable amount of time. Would you agree to that solution?

**Comment by Skydiver777** [comment]
Hi, thanks for looking into this case. I cannot tell how complicated it would be - all I see from the frontend is, that inside the basket custom products (non premium plug in) already offers a link to go back to the customized product - but it misses an update button there. I have no clue what would happen if your "change variant" would pick up this Product URL and show it in the modal. May be complicated, may be easy :-)

For me the only reason I have installed "change variant" was because I hoped I can use it for editing custom products from the basket, as we are selling over 60% modified Products.

Best 
Gabriel

**Comment by dneustadt** [comment]
Decided to close this for the moment since it seems to be an issue with a third-party plugin and even more so an issue within that plugin itself. I'd recommend you contact the developer of the third-party plugin to ask if they are able to enhance their product with the desired feature.
